# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LastFM-App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LastFM-App
  pod 'Alamofire', '~> 5.2'
  pod 'AlamofireImage', '~> 4.1'

  target 'LastFM-AppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
